CREATE TABLE LFA1(
  LIFNR VARCHAR2(10),
  NAME1 VARCHAR2(35),
  ORT01 VARCHAR2(35),
  PSTLZ VARCHAR2(10),
  REGION_ID NUMBER(3),
  SORTL VARCHAR2(10),
  STRAS VARCHAR2(35),
  ADRNR VARCHAR2(10),
  MCOD1 VARCHAR2(25),
  MC0D3 VARCHAR2(25),
  ERDAT DATE,
  ERNAM VARCHAR(12),
  KTOKK VARCHAR(4),
  SPRAS VARCHAR(3),
  TELF1 VARCHAR(16),
  TELF2 VARCHAR(16),
  TELFX VARCHAR(31),
  VAT_RNUM VARCHAR(20),
  DUEFL VARCHAR(1),
  ID_ERP VARCHAR(10),
  COUNTRY_ID NUMBER(3),
  TAX_NUMBER VARCHAR(15)
);

ALTER TABLE LFA1 
ADD CONSTRAINT VENDOR_ID_PK PRIMARY KEY(LIFNR);

ALTER TABLE LFA1 
ADD CONSTRAINT REGION_FK
  FOREIGN KEY(REGION_ID)
  REFERENCES M_REGION(ID);
  
ALTER TABLE LFA1 
ADD CONSTRAINT COUNTRY_FK
  FOREIGN KEY(COUNTRY_ID)
  REFERENCES M_COUNTRY(ID);

CREATE TABLE MARA(
  MATNR VARCHAR2(18) PRIMARY KEY,
  MTART VARCHAR2(4),
  MBRSH VARCHAR2(1),
  MAKTX VARCHAR2(40),
  MEIS VARCHAR2(3),
  MATKL VARCHAR2(9)
);

CREATE TABLE EBAN(
  BANFN VARCHAR2(10) PRIMARY KEY,
  BSART VARCHAR2(4),
  BNFPO NUMBER(5),
  MATNR VARCHAR2(18),
  TXZ01 VARCHAR2(18),
  WERKS VARCHAR2(4),
  PSPNR NCHAR,
  PREIS NUMBER(11,4),
  CONSTRAINT MATERIAK_PK
    FOREIGN KEY (MATNR) REFERENCES MARA (MATNR)
);



------------------------------------------------------------------------------


CREATE TABLE PERUSAHAAN
(
  ID                   NUMBER(20),
  NPWP                 VARCHAR2(2000 BYTE),
  NAMA                 VARCHAR2(2000 BYTE),
  ALAMAT               VARCHAR2(2000 BYTE),
  EMAIL                VARCHAR2(2000 BYTE),
  TELEPON              VARCHAR2(2000 BYTE),
  KEKAYAAN_BERSIH      NUMBER(20,2),
  CP                   VARCHAR2(2000 BYTE),
  CP_HP                VARCHAR2(2000 BYTE),
  USERNAME             VARCHAR2(2000 BYTE),
  PASSWORD             VARCHAR2(2000 BYTE),
  PERTANYAAN           VARCHAR2(2000 BYTE),
  JAWABAN              VARCHAR2(40 BYTE),
  WAKTU_AKTIVASI       DATE,
  KOTA                 VARCHAR2(2000 BYTE),
  FAX                  VARCHAR2(2000 BYTE),
  BOLEH_HAPUS_AHLI     NUMBER                   DEFAULT 0,
  STATE                NUMBER                   DEFAULT 0,
  CREATED_AT           DATE,
  UPDATED_AT           DATE,
  DPP_NOMOR            VARCHAR2(2000 BYTE),
  DPP_TANGGAL_MULAI    DATE,
  DPP_TANGGAL_BERLAKU  DATE,
  DPP_STATUS           INTEGER                  DEFAULT 0,
   ID_ERP  VARCHAR2(32),
   VAT_RNUM VARCHAR2(20),
   REGION_ID NUMBER(3),
   COUNTRY_ID NUMBER(3),
   TAX_NUMBER VARCHAR2(16),
   FLAG INTEGER DEFAULT 0
);

ALTER TABLE PERUSAHAAN 
ADD CONSTRAINT ID_PERUSAHAAN_PK PRIMARY KEY(ID);

CREATE TABLE M_REGION(
  ID NUMBER(3) PRIMARY KEY,
  REGION_NAME VARCHAR(32)
);

CREATE TABLE M_COUNTRY(
  ID NUMBER(3) PRIMARY KEY,
  COUNTRY_KEY VARCHAR(3)
);
